import sqlite3
import tkinter as tk
def chetna():
    name=Entry_name.get()
    Email=Entry_Email.get()
    contactno=Entry_contactno.get()
    purpose=Entry_purpose.get()
    password=Entry_password.get()
    connect=sqlite3.connect("data.db")
    cursor=connect.cursor()
    cursor.execute('''create table if not exists signin(name text,Email text,contactno integer,purpose text,password text_notnull)''')
    cursor.execute('''insert into signin(name,Email,contactno,purpose,password) values (?,?,?,?,?)''',(name,Email,contactno,purpose,password))
    connect.commit()
    connect.close()
    #tkinter
import tkinter as tk
root=tk.Tk()
Label_name=tk.Label(root,text="SIGNUP")
Label_name.pack()
Label_name=tk.Label(root,text="name")
Label_name.pack()
Entry_name=tk.Entry(root)
Entry_name.pack()
Label_contactno=tk.Label(root,text="contactno")
Label_contactno.pack()
Entry_contactno=tk.Entry(root)
Entry_contactno.pack()
Label_Email=tk.Label(root,text="Email")
Label_Email.pack()
Entry_Email=tk.Entry(root)
Entry_Email.pack()
Label_purpose=tk.Label(root,text="purpose")
Label_purpose.pack()
Entry_purpose=tk.Entry(root)
Entry_purpose.pack()
Label_password=tk.Label(root,text="password")
Label_password.pack()
Entry_password=tk.Entry(root)
Entry_password.pack()
submit_Button=tk.Button(root,text="submit",command=chetna)
submit_Button.pack()
root.mainloop()
